update

diff --git a/functions b/functions
--- a/functions
+++ b/functions
@@ -2,7 +2,7 @@
 
 ### openspace synthia bootstrap framework
 ### [https://github.com/openspace42/synthia]
-### v0.3.2
+### v0.3.3
 
 dna_version="v0.3.14"
 
@@ -21,15 +21,19 @@ synthia-define_vars() {
 	## set this to 'disabled' to disable local backups and only upload to S3
 	## [useful if your project handles large amounts of data for example].
 	## S3 must be set up by the user or else backups will not work at all.
+	## this is only the default, which will be suggested to the user during
+	## install, and it can be overridden.
 
-	export backup_locally_mode="disabled"
+	export backup_locally_mode_default="disabled"
 
-	## set this to 'y' if your project stores no data on end users' machines
+	## set this to 'n' if your project stores no data on end users' machines
 	## that could go lost during a re-install or update.
-	export skip_install_time_backup="y"
+
+	export backup_prompt_during_install="n"
 
 	## set this to the directory that has the most impactful size when
 	## performing a backup [such as '/var/www/' for nginx-related projects].
+
 	export backup_ref_dir="/home/user-data"
 
 	############################################################################
@@ -196,79 +200,52 @@ synthia-source_dna() {
 ######################## Insert project functions here #########################
 ################################################################################
 
-backup_locally_loop() {
+synthia_backup() {
 
-    ### Copy conf dir to $tmp_backup_dir
+	############################################################################
 
-	cp -r "${conf_dir}" "${tmp_backup_dir}/conf/"
-
-	### Add hardcoded sites to exclude to the user-specified ones
-
-	backup_exclude_sites="22222, html, roundcubemail, ${backup_exclude_sites}"
-
-	### For every site...
-
-	for site in $ee_www_dir/*
-	do
-
-		if [ -d "$site" ]
-		then
-
-			this_site="$(echo "$site" | sed "s|${ee_www_dir}/||")"
-
-			### If this site is not on the exclusion list...
-
-			if [ "${backup_exclude_sites/$this_site}" = "${backup_exclude_sites}" ]
-			then
-
-				dna-echo -m "*] Now evaluating site: | ${g}$this_site${n-} |:"
-
-				### Determine target backup directory for this site
-
-				this_site_dir="${tmp_backup_dir}/data/${this_site}"
-				mkdir -p "${this_site_dir}"
-
-				wpconfigfile="$site/wp-config.php"
-
-				### If a wp-config file is found...
-
-				if [ -f $wpconfigfile ]
-				then
-
-					### This is a wp site
-
-					dna-echo -m "   Proceeding with ${l-}wordpress${n-} site backup..."
-
-					wp_db_name=`cat $wpconfigfile | grep DB_NAME | cut -d \' -f 4`
-					wp_db_user=`cat $wpconfigfile | grep DB_USER | cut -d \' -f 4`
-					wp_db_pass=`cat $wpconfigfile | grep DB_PASSWORD | cut -d \' -f 4`
-
-					mysqldump -u ${wp_db_user} -p${wp_db_pass} ${wp_db_name} > "${this_site_dir}/mysqldump.sql"
-
-					cp "${wpconfigfile}" "${this_site_dir}/wp-config.php"
-
-				else
-
-					dna-echo -m "   Proceeding with ${m-}NON wordpress${n-} site backup..."
-
-				fi
-
-				### Backup htdocs dir
-
-				rsync -aAXx --exclude backup --exclude conf --exclude logs "$site"/ "$this_site_dir"
-
-				dna-echo -s "   Finished backup for | ${n-}${this_site}${g-} |."
-
-			else
-
-				dna-echo -m "*] Site | ${r-}${this_site}${n-} | is on the exclusion list."
-				dna-echo -e "Skipping..."
-
-			fi
-
-		fi
-
+	while getopts ":s" arguments; do
+	    case $arguments in
+			s)	skip_install_complete_check="-s"
+				;;
+			\?)	dna-echo -e "Invalid option | ${n-}-$OPTARG${r-} | for function | ${n-}${FUNCNAME[0]}${r-} |."
+				dna-exit
+				;;
+		esac
 	done
+	OPTIND=1
+
+	############################################################################
+
+	dna-backuprestore_check_set_lockfile
+
+	############################################################################
+
+	## perform pre-backup operations
+
+	service nginx stop || true
+	service php7.2-fpm stop || true
+
+	############################################################################
+
+	if ! dna-backuprestore_backup_subloop
+	then
+
+		dna-echo -e "backup subloop function exited with errors."
+		dna-echo -m "continuing anyway to perform post-backup operations if any and exit backup function gracefully."
+
+	fi
+
+	############################################################################
+
+	## perform post-backup operations
+
+	service nginx start || true
+	service php7.2-fpm start || true
+
+	############################################################################
+
+	dna-backuprestore_backup_cleanup
 
 }
 
@@ -711,151 +688,6 @@ restore_loop() {
 
 }
 
-choose_local_user() {
-
-	currusers="$(cat /etc/passwd | cut -d: -f 1,3,6 | grep "[1-9][0-9][0-9][0-9]" | grep "/home" | cut -d: -f1)"
-
-	declare -a options=( ${currusers} )
-
-	if [ -z "${currusers}" ]
-	then
-		dna-echo -e "No NON-system users found."
-		dna-echo -m "Run the | ${o-}add-user${n-} | command first."
-		dna-exit
-	fi
-
-	accept="n"
-	until [ "${accept}" = "y" ]
-	do
-
-		select sel_user in "${options[@]}"
-		do
-			echo
-			IFS=' ' read name ip <<< $sel_user
-			test -n "${sel_user}" && break
-			echo ">>> Invalid Selection"
-		done
-
-		dna-echo -m "User ${sel_user} selected."
-
-		valid="n"
-		until [ "${valid}" = "y" ]
-		do
-			read -n 1 -rp "${b}Is this the correct user?${x} (${b}Y${x}[es]/${b}n${x}[o]/${b}e${x}[xit]) " answer;
-			case $answer in
-				"")
-				echo
-				valid=y
-				accept=y
-				;;
-				y)
-				echo -e "\\n"
-				valid=y
-				accept=y
-				;;
-				n)
-				echo -e "\\n"
-				echo "${b}No problem, please select your desired user again now...${x}"
-				echo
-				valid=y
-				accept=n
-				;;
-				e)
-				echo -e "\\n"
-				echo "${b}Exiting...${x}"
-				echo
-				exit
-				;;
-				*)
-				echo -e "\\n"
-				echo "${b}Invalid option. Retry...${x}"
-				echo
-				valid=n
-				accept=n
-				;;
-			esac
-		done
-
-	done
-
-}
-
-choose_local_site() {
-
-	if [ ! -d "${www_dir}" ]
-	then
-		dna-echo -e "Local backups directory [${www_dir}] not found."
-		dna-exit
-	fi
-
-	if [ -z "$(ls -A ${www_dir})" ]
-	then
-		dna-echo -e "No sites found in | ${www_dir} |.."
-		dna-exit
-	fi
-
-	choice="${b}Now choose the site you'd like to provide access to: ${x}"
-	echo "$choice"
-	echo
-
-	accept=n
-	until [ $accept = "y" ]
-	do
-
-		select sel_site in $www_dir/*
-		do
-			echo
-			test -n "$sel_site" && break
-			echo ">>> Invalid Selection"
-		done
-
-		echo "${b}Site $sel_site selected.${x}"
-		echo
-
-		valid=n
-		until [ $valid = "y" ]
-		do
-			read -n 1 -rp "${b}Is this the correct site?${x} (${b}Y${x}[es]/${b}n${x}[o]/${b}e${x}[xit]) " answer;
-			case $answer in
-				"")
-				echo
-				valid=y
-				accept=y
-				;;
-				y)
-				echo -e "\\n"
-				valid=y
-				accept=y
-				;;
-				n)
-				echo -e "\\n"
-				echo "${b}No problem, please select your desired site again now...${x}"
-				echo
-				valid=y
-				accept=n
-				;;
-				e)
-				echo -e "\\n"
-				echo "${b}Exiting...${x}"
-				echo
-				exit
-				;;
-				*)
-				echo -e "\\n"
-				echo "${b}Invalid option. Retry...${x}"
-				echo
-				valid=n
-				accept=n
-				;;
-			esac
-		done
-
-	done
-
-	sel_site_name=${sel_site#/var/www/}
-
-}
-
 ################################################################################
 ################################################################################
 ################################################################################
@@ -865,9 +697,6 @@ synthia-perform_installation() {
 	############################################################################
 	################### Add your install-time functions here ###################
 	############################################################################
-
-	### This function is not EEv4-ready
-	### dna-install_easyengine
 
 	dna-set_admin_email
 	dna-setup_backup_restore
